name: fixgo-api-cd

on:
  push:
    branches: 
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1

    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore 

    - name: Publish
      run: dotnet publish ./gizmogeo.API/gizmogeo.API.csproj -o ${{env.DOTNET_ROOT}}/api --no-build
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: api-aftifact
        path: ${{env.DOTNET_ROOT}}/api

  deploy-prod:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4.1.3
        with:
          name: api-aftifact
          
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3.0.0
        with:
          app-name: "fixgo-api"
          publish-profile: ${{ secrets.PUBLISH_PROFILE_PROD }}


