name: fixgo-api-cd

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Publish
        run: dotnet publish ./gizmogeo.API/gizmogeo.API.csproj -c Release -o ./publish

      - name: Zip the published app
        run: zip -r publish.zip ./publish

      - name: Deploy to Azure Web App (ZipDeploy)
        uses: azure/webapps-deploy@v3
        with:
          app-name: "fixgo-api"
          publish-profile: ${{ secrets.PUBLISH_PROFILE_PROD }}
          package: publish.zip
